version: 0.2
env:
  variables:
    SAM_CLI_TELEMETRY: '0'
phases:
  pre_build:
    commands:
      - mkdir ~/.aws
      - echo -e "[profile account-role]\nrole_arn = ${ACCOUNT_ROLE}\ncredential_source = EcsContainer" >> ~/.aws/config
  build:
    commands:
      - envsubst < samconfig.toml.template > samconfig.toml
      - sam build
      - sam package
      - sam deploy --profile account-role
