version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam build --use-container
      - sam package --template-file template.yaml --s3-bucket $LAMBDA_BUCKET_NAME --s3-prefix trial-randomisation-api --output-template-file packaged.yml
artifacts:
  files:
    - packaged.yml