AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  trial-randomisation-api
  Endpoints for /n_of_1
Parameters:
  CertificateArn:
    Type: String
    Default: ''
  DomainName:
    Type: String
    Default: ''
  HostedZoneName:
    Type: String
    Default: ''
Conditions:
  CreateDomain: !And
    - !Not [!Equals [!Ref CertificateArn, '']]
    - !Not [!Equals [!Ref DomainName, '']]
    - !Not [!Equals [!Ref HostedZoneName, '']]
Globals:
  Function:
    Timeout: 60
    MemorySize: 2048
Resources:
  NOfOneFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: n_of_1/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /n_of_1/v1
            Method: post
  ApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Condition: CreateDomain
    Properties:
      RegionalCertificateArn: !Ref CertificateArn
      DomainName: !Ref DomainName
      EndpointConfiguration:
        Types:
        - REGIONAL
  ApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Condition: CreateDomain
    Properties:
      DomainName: !Ref ApiDomainName
      RestApiId: !Ref ServerlessRestApi
      Stage: !Ref ServerlessRestApiProdStage
    DependsOn: NOfOneFunction
  ApiDomain:
    Type: AWS::Route53::RecordSetGroup
    Condition: CreateDomain
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          DNSName: !GetAtt ApiDomainName.RegionalDomainName
          HostedZoneId: !GetAtt ApiDomainName.RegionalHostedZoneId
Outputs:
  NOfOneApi:
    Description: "API Gateway endpoint URL for Prod stage for NOfOne function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/n_of_1/v1/"
  NOfOneEndpoint:
    Condition: CreateDomain
    Description: "n-of-1 endpoint"
    Value: !Sub "https://${DomainName}/n_of_1/v1/"
  NOfOneFunction:
    Description: "NOfOne Function ARN"
    Value: !GetAtt NOfOneFunction.Arn
  NOfOneFunctionIamRole:
    Description: "NOfOne Function IAM Role"
    Value: !GetAtt NOfOneFunctionRole.Arn

